Algoritmo "idade"

Var

nome1, nome2: caractere
idade1, idade2, media: real

Inicio

escreva ("Escreva o nome da 1ª pessoa: ")
leia (nome1)
escreva ("Escreva a idade da 1ª pessoa: ")
leia (idade1)
escreva ("Escreva o nome da 2ª pessoa: ")
leia (nome2)
escreva ("Esvreva a idade da 2ª pessoa: ")
leia (idade2)
media <- (idade1+idade2)/2
escreval ("A idade média de ", nome1, " e ", nome2, " é de ", media, " anos")

Fimalgoritmo