Algoritmo "medidas"

Var

A, B, C, quadrado, triangulo, trapezio: real

Inicio

escreva ("Digite a medida A: ")
leia (A)
escreva ("Digite a medida B: ")
leia (B)
escreva ("Digite a medida C: ")
leia (C)

quadrado <- Exp (A,2)
triangulo <- A * B / 2
trapezio <- ((A + B) * C ) / 2

escreval ("A Área do Quadrado é: ", quadrado:6:4)
escreval ("A Área do Triângulo é: ", triangulo: 6:4)
escreval ("A Área do trapezio é: ", trapezio:6:4)

Fimalgoritmo